services:
  adguard-home-exporter:
    image: ghcr.io/attilagyorffy/prometheus-exporter-adguard-home:latest
    container_name: adguard-home-exporter
    environment:
      - ADGUARD_URL=http://adguard:3000
      - ADGUARD_USERNAME=admin
      - ADGUARD_PASSWORD=${ADGUARD_PASSWORD}
      - LISTEN_PORT=9617
      - ADGUARD_TOP_N=10
      - LOG_LEVEL=info
    ports:
      - "9617:9617"
    restart: unless-stopped
